openapi: 3.0.2
info:
  description: A sample API to illustrate OpenAPI concepts
  title: Sample API
  version: 1.0.0
servers:
- url: /
paths:
  /:
    get:
      description: Returns a list of stuff
      responses:
        "200":
          description: Successful response
components:
  schemas: {}
