openapi: 3.0.4
info:
  title: GenAI MicroService - OpenAPI 3.0
  version: 0.0.1
servers:
- url: http://127.0.0.1:8000
- url: http://localhost:8000
tags:
- description: Direct interaction with the vector DB
  name: embedding
- description: Direct interaction with the LLM
  name: generation
paths:
  /embed:
    post:
      description: Create a new study program and embed the modules.
      operationId: createStudyProgram
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudyProgram'
        required: true
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid status value
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      summary: Create a new study program and embed the modules.
      tags:
      - embedding
  /embed/{id}:
    delete:
      description: Delete a study program
      operationId: deleteStudyProgram
      parameters:
      - description: ID of the study program that should be deleted
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          description: Study program deleted
        "400":
          description: Invalid study program id value
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      summary: Delete a study program
      tags:
      - embedding
    post:
      description: Add new modules to a study program.
      operationId: updateStudyProgram
      parameters:
      - description: ID of the study program
        explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Modules'
        required: true
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid status value
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      summary: Add new modules to a study program
      tags:
      - embedding
  /chat:
    get:
      description: Communicate with the ChatBot making use of streamed responses
      operationId: streamChat
      parameters:
      - description: Chat Prompt
        explode: true
        in: query
        name: prompt
        required: true
        schema:
          default: Write a poem
          type: string
        style: form
      - description: Conversation ID
        explode: true
        in: query
        name: id
        required: true
        schema:
          default: 420
          type: integer
        style: form
      responses:
        "200":
          content:
            text/event-stream:
              schema:
                example: |
                  data: Hello

                  data: World
                type: string
          description: A stream of message tokens
      summary: Communicate with the ChatBot
      tags:
      - generation
components:
  schemas:
    StudyProgram:
      example:
        id: 0
        modules:
        - 6
        - 6
      properties:
        id:
          format: int64
          title: id
          type: integer
        modules:
          items:
            format: int64
            type: integer
          title: modules
          type: array
      required:
      - id
      - modules
      title: StudyProgram
      type: object
    Modules:
      items:
        format: int64
        type: integer
      title: modules
      type: array
    Error:
      example:
        code: code
        message: message
      properties:
        code:
          title: code
          type: string
        message:
          title: message
          type: string
      required:
      - code
      - message
      title: Error
      type: object
