creation_rules:

  - path_regex: ^nix/targets/cluster/secrets/.*worker-1\.ya?ml$
    key_groups:
      - age:
          - age12epp4tlgu0mgj952ywtjft8hdxg5vvpp5u0sny3lprhmezeufpkq8yemqs
          - age1rytcf06at443cfuc0q463ljkszh63qhxs3vgaqq7ht9zl0y57cmqy7cdxe
          - age1qtg6d3htm8yt3eeq5hwrurkdg50jsl9l5ke9t2ynsk79rq2u5v4s3fgadg
        pgp:
          - E12CB38E6FC75F203B973FE8C1FD5ADC93DB2220
  
  - path_regex: ^nix/targets/cluster/secrets/.*worker-2\.ya?ml$
    key_groups:
      - age:
          - age1nn383csq0xrjcdnn9atvklg65aj6w3rz70lr3kyg8fx0al2z3c5qd0rx8r
          - age1rytcf06at443cfuc0q463ljkszh63qhxs3vgaqq7ht9zl0y57cmqy7cdxe
          - age1qtg6d3htm8yt3eeq5hwrurkdg50jsl9l5ke9t2ynsk79rq2u5v4s3fgadg
        pgp:
          - E12CB38E6FC75F203B973FE8C1FD5ADC93DB2220
  
  - path_regex: ^nix/targets/cluster/secrets/.*loadbalancer-1\.ya?ml$
    key_groups:
      - age:
          - age1tr04gshu2u3rppsydgv444jfpdph07ul9hgw5r0xpder7ttedgps7na7he
          - age1rytcf06at443cfuc0q463ljkszh63qhxs3vgaqq7ht9zl0y57cmqy7cdxe
          - age1qtg6d3htm8yt3eeq5hwrurkdg50jsl9l5ke9t2ynsk79rq2u5v4s3fgadg
        pgp:
          - E12CB38E6FC75F203B973FE8C1FD5ADC93DB2220
  
  - path_regex: ^nix/targets/cluster/secrets/.*control-1\.ya?ml$
    key_groups:
      - age:
          - age1s6gej2um4yjq8ptjyhf3m4f55yfumhze5qdm80ru64yyzdlt8usq82v7uj
          - age1rytcf06at443cfuc0q463ljkszh63qhxs3vgaqq7ht9zl0y57cmqy7cdxe
          - age1qtg6d3htm8yt3eeq5hwrurkdg50jsl9l5ke9t2ynsk79rq2u5v4s3fgadg
        pgp:
          - E12CB38E6FC75F203B973FE8C1FD5ADC93DB2220
  
  - path_regex: ^nix/targets/cluster/secrets/.*control-2\.ya?ml$
    key_groups:
      - age:
          - age13k4zant4a6sws9vc9falhlgnsm9zr2y8ery8uzeqejnuct0tk9nspeunnr
          - age1rytcf06at443cfuc0q463ljkszh63qhxs3vgaqq7ht9zl0y57cmqy7cdxe
          - age1qtg6d3htm8yt3eeq5hwrurkdg50jsl9l5ke9t2ynsk79rq2u5v4s3fgadg
        pgp:
          - E12CB38E6FC75F203B973FE8C1FD5ADC93DB2220
  
  - path_regex: ^nix/targets/cluster/secrets/.*control-3\.ya?ml$
    key_groups:
      - age:
          - age17tuhruh4yuedjvhqwq727hhvaxgyj8wr49twu6f63lxm3s38rdyqf7ssp8
          - age1rytcf06at443cfuc0q463ljkszh63qhxs3vgaqq7ht9zl0y57cmqy7cdxe
          - age1qtg6d3htm8yt3eeq5hwrurkdg50jsl9l5ke9t2ynsk79rq2u5v4s3fgadg
        pgp:
          - E12CB38E6FC75F203B973FE8C1FD5ADC93DB2220
  
  - path_regex: ^nix/targets/cluster/secrets/.*etcd-1\.ya?ml$
    key_groups:
      - age:
          - age1wpup242zy0kmdg6a9j39slgpq7jy9kv6n5s6ce0l5cgh6xexvcnqp4hsrc
          - age1rytcf06at443cfuc0q463ljkszh63qhxs3vgaqq7ht9zl0y57cmqy7cdxe
          - age1qtg6d3htm8yt3eeq5hwrurkdg50jsl9l5ke9t2ynsk79rq2u5v4s3fgadg
        pgp:
          - E12CB38E6FC75F203B973FE8C1FD5ADC93DB2220
  
  - path_regex: ^nix/targets/cluster/secrets/.*etcd-2\.ya?ml$
    key_groups:
      - age:
          - age14t0lp07pcgfnqvva3alw5v9f6hv58mferrg2yym39chpt92r036sdflawe
          - age1rytcf06at443cfuc0q463ljkszh63qhxs3vgaqq7ht9zl0y57cmqy7cdxe
          - age1qtg6d3htm8yt3eeq5hwrurkdg50jsl9l5ke9t2ynsk79rq2u5v4s3fgadg
        pgp:
          - E12CB38E6FC75F203B973FE8C1FD5ADC93DB2220
  
  - path_regex: ^nix/targets/cluster/secrets/.*etcd-3\.ya?ml$
    key_groups:
      - age:
          - age1egqswkszq7rpm043cxfzcm4sqj969gzlvjl2tr5mgwz6ue3szfyq4h4nus
          - age1rytcf06at443cfuc0q463ljkszh63qhxs3vgaqq7ht9zl0y57cmqy7cdxe
          - age1qtg6d3htm8yt3eeq5hwrurkdg50jsl9l5ke9t2ynsk79rq2u5v4s3fgadg
        pgp:
          - E12CB38E6FC75F203B973FE8C1FD5ADC93DB2220
  
  
  - path_regex: ^nix/targets/dev/secrets/.*\.ya?ml$
    key_groups: 
      - age:
          - age1dttmyeya6pssd34gmtuuyfwa3qk5umn3xvc3ppkkxxuqd303jy4ssr0jyx
          - age1rytcf06at443cfuc0q463ljkszh63qhxs3vgaqq7ht9zl0y57cmqy7cdxe
          - age1qtg6d3htm8yt3eeq5hwrurkdg50jsl9l5ke9t2ynsk79rq2u5v4s3fgadg
        pgp:
          - E12CB38E6FC75F203B973FE8C1FD5ADC93DB2220
  
  - path_regex: ^nix/targets/.*\.ya?ml$
    key_groups: 
      - age:
          - age1rytcf06at443cfuc0q463ljkszh63qhxs3vgaqq7ht9zl0y57cmqy7cdxe
          - age1qtg6d3htm8yt3eeq5hwrurkdg50jsl9l5ke9t2ynsk79rq2u5v4s3fgadg
        pgp:
          - E12CB38E6FC75F203B973FE8C1FD5ADC93DB2220
