keys:
  - &dev age1dttmyeya6pssd34gmtuuyfwa3qk5umn3xvc3ppkkxxuqd303jy4ssr0jyx
  - &floriannadam age1rytcf06at443cfuc0q463ljkszh63qhxs3vgaqq7ht9zl0y57cmqy7cdxe
  - &ghoscht age1qtg6d3htm8yt3eeq5hwrurkdg50jsl9l5ke9t2ynsk79rq2u5v4s3fgadg 
  - &mikilio E12CB38E6FC75F203B973FE8C1FD5ADC93DB2220
creation_rules:
  - path_regex: nix/targets/dev/secrets/*
    key_groups:
      - pgp:
          - *mikilio
        age:
          - *dev
          - *floriannadam
          - *ghoscht
  - path_regex: nix/targets/admins/secrets/*
    key_groups:
      - pgp:
          - *mikilio
        age:
          - *floriannadam
          - *ghoscht
