apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genai-milvus
  namespace: "{{ .Values.tumid }}-team-nixops"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-rbd-sc
