apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai
  # namespace: ""
spec:
  replicas: {{ .Values.genai.replicaCount }}
  selector:
    matchLabels:
      app: genai-selector
  template:
    metadata:
      labels:
        app: genai-selector
    spec:
      containers:
        - name: etcd
          image: "quay.io/coreos/etcd:v3.5.18"
          command: ["etcd"]
          args: ["-advertise-client-urls=http://localhost:2379",  "-listen-client-urls", "http://0.0.0.0:2379",  "--data-dir", "/etcd"]
          imagePullPolicy: {{ .Values.genai.image.pullPolicy }}
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            exec:
              command: ["CMD", "etcdctl", "endpoint", "health"]
            periodSeconds: 30
            timeoutSeconds: 20
            failureThreshold: 3
          env:
            - name: ETCD_AUTO_COMPACTION_MODE
              value: "revision"
            - name: ETCD_AUTO_COMPACTION_RETENTION
              value: "1000"
            - name: ETCD_QUOTA_BACKEND_BYTES
              value: "4294967296"
            - name: ETCD_SNAPSHOT_COUNT
              value: "50000"
          volumeMounts:
            - name: etcd-data
              mountPath: /etcd
        - name: minio
          image: "minio/minio:RELEASE.2023-03-20T20-16-18Z"
          command: ["minio"]
          args: ["server", "/minio_data", "--console-address", ":9001"]
          imagePullPolicy: {{ .Values.genai.image.pullPolicy }}
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            exec:
              command: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            periodSeconds: 30
            timeoutSeconds: 20
            failureThreshold: 3
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: root_user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: root_password
          ports:
            - containerPort: 9000
              name: minio-api
            - containerPort: 9001
              name: minio-dash
          volumeMounts:
            - name: minio-data
              mountPath: /minio_data
        - name: milvus
          image: "milvusdb/milvus:v2.5.12"
          command: ["milvus"]
          args: [ "run", "standalone" ]
          imagePullPolicy: {{ .Values.genai.image.pullPolicy }}
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            exec:
              command: ["curl", "-f", "http://localhost:9091/healthz"]
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 20
            failureThreshold: 3
          env:
            - name: MINIO_REGION
              value: "us-east-1"
            - name: ETCD_ENDPOINTS
              value: "localhost:2379"
            - name: MINIO_ADDRESS
              value: "localhost:9000"
          ports:
            - containerPort: 19530
              name: milvus-api
            - containerPort: 9091
              name: milvus-dash
          volumeMounts:
            - name: milvus-data
              mountPath: /var/lib/milvus
        - name: genai
          image: "{{ .Values.genai.image.repository }}:{{ .Values.genai.image.tag }}"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: LLM_API_URL
              value: "https://gpu.aet.cit.tum.de/ollama"
            - name: LLM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: genai
                  key: llm_api_key
            - name: LLM_CHAT_MODEL
              value: "llama3.3:latest"
            - name: LLM_EMBEDDING_MODEL
              value: "deepseek-r1:70b"
            - name: LLM_CHAT_TEMP
              value: "0.5"
            - name: CORS_ORIGINS
              value: "https://api.nixops-devops25.student.k8s.aet.cit.tum.de"
          ports:
            - containerPort: {{ .Values.genai.service.targetPort }}
              name: genai-api
      volumes:
      - name: milvus-data
        persistentVolumeClaim:
          claimName: milvus
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio
      - name: etcd-data
        persistentVolumeClaim:
          claimName: etcd
