apiVersion: v1
kind: Service
metadata:
  name: genai-service
  # namespace: "{{ .Values.tumid }}-devops25"
spec:
  selector:
    app: genai-selector
  ports:
    - port: {{ .Values.genai.service.port }}
      targetPort: {{ .Values.genai.service.targetPort }}
      protocol: TCP
  type: {{ .Values.genai.service.type }}

