apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai
  # namespace: ""
spec:
  replicas: {{ .Values.genai.replicaCount }}
  selector:
    matchLabels:
      app: genai-selector
  template:
    metadata:
      labels:
        app: genai-selector
    spec:
      containers:
        - name: genai
          image: "{{ .Values.genai.image.repository }}:{{ .Values.genai.image.tag }}"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: LLM_API_URL
              value: "https://gpu.aet.cit.tum.de/ollama"
            - name: LLM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: genai
                  key: llm_api_key
            - name: LLM_CHAT_MODEL
              value: "llama3.3:latest"
            - name: LLM_EMBEDDING_MODEL
              value: "deepseek-r1:70b"
            - name: LLM_CHAT_TEMP
              value: "0.3"
            - name: CORS_ORIGINS
              value: "https://nixops-devops25.student.k8s.aet.cit.tum.de"
          ports:
            - containerPort: {{ .Values.genai.service.targetPort }}
              name: genai-api
