{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "nixops-ingress"
  namespace: "{{ .Values.MonitoringNamespace }}"
  {{- $annotations := .Values.ingress.annotations | default dict }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - "stats.nixops-devops25.student.k8s.aet.cit.tum.de"
      secretName: "nixops-devops25-tls"
  {{- end }}
  rules:
    - host: "stats.nixops-devops25.student.k8s.aet.cit.tum.de"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitoring-service
                port:
                  number: 3000
{{- end }}
