apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nixops-scraper-postgres
  namespace: "{{ .Values.ServiceNamespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
