apiVersion: v1
kind: Service
metadata:
  name: scraper-db-service
  namespace: "{{ .Values.ServiceNamespace }}"
spec:
  selector:
    app: scraper-db
  ports:
    - port: 5432
      targetPort: 5432

