apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scraper-db-pvc
  namespace: "{{ .Values.ServiceNamespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

