openapi: 3.0.4
info:
  title: GenAI MicroService - OpenAPI 3.0
  version: 0.0.1
servers:
  - url: http://127.0.0.1:8000
  - url: http://localhost:8000
tags:
  - name: embedding
    description: Direct interaction with the vector DB
  - name: generation
    description: Direct interaction with the LLM

paths:
  /embed:
    post:
      summary: Create a new study program and embed the modules.
      description: Create a new study program and embed the modules.
      operationId: createStudyProgram
      tags:
        - embedding
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudyProgram'
        required: true
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid status value
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /embed/{id}:
    post:
      summary: Add new modules to a study program
      description: Add new modules to a study program.
      operationId: updateStudyProgram
      tags:
        - embedding
      parameters:
        - name: id
          in: path
          description: ID of the study program
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Modules'
        required: true
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid status value
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      tags:
        - embedding
      summary: Delete a study program
      description: Delete a study program
      operationId: deleteStudyProgram
      parameters:
        - name: id
          in: path
          description: ID of the study program that should be deleted
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Study program deleted
        '400':
          description: Invalid study program id value
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /chat:
    get:
      summary: Communicate with the ChatBot
      description: Communicate with the ChatBot making use of streamed responses
      operationId: streamChat
      tags:
        - generation
      parameters:
        - name: prompt
          in: query
          description: Chat Prompt
          required: true
          schema:
            type: string
            default: Write a poem
        - name: id
          in: query
          description: Conversation ID
          required: true
          schema:
            type: integer
            default: 420
      responses:
        '200':
          description: A stream of message tokens
          content:
            text/event-stream:
              schema:
                type: string
                example: |
                  data: Hello

                  data: World
components:
  schemas:
    StudyProgram:
      type: object
      properties:
        id:
          type: integer
          format: int64
        modules:
          $ref: '#/components/schemas/Modules'
      required:
        - id
        - modules
    Modules:
        type: array
        items:
          type: integer
          format: int64
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
