openapi: 3.0.2
info:
  version: 1.0.0
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
paths:
  /:
    get:
      description: Returns a list of stuff              
      responses:
        '200':
          description: Successful response
