openapi: 3.0.4
info:
  title: GenAI MicroService - OpenAPI 3.0
  version: 0.0.1
servers:
  - url: http://127.0.0.1:8000
  - url: http://localhost:8000
tags:
  - name: embedding
    description: Direct interaction with the vector DB
  - name: generation
    description: Direct interaction with the LLM

paths:
  /embed:
    post:
      summary: Create a new study program and embed the modules.
      description: Create a new study program and embed the modules.
      operationId: createStudyProgram
      tags:
        - embedding
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StudyProgram"
        required: true
      responses:
        "200":
          description: successful operation
        "400":
          description: Invalid status value
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /embed/studyPrograms:
    get:
      summary: Get all scraped study programs
      description: Get all scraped study programs and matching semesters
      operationId: fetchStudyPrograms
      tags:
        - embedding
      responses:
        "200":
          description: A stream of message tokens
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StudyProgramSelectorItem"

  /chat:
    get:
      summary: Communicate with the ChatBot
      description: Communicate with the ChatBot making use of streamed responses
      operationId: streamChat
      tags:
        - generation
      parameters:
        - name: prompt
          in: query
          description: Chat Prompt
          required: true
          schema:
            type: string
            default: Write a poem
        - name: convId
          in: query
          description: Conversation ID
          required: true
          schema:
            type: integer
            default: 420
        - name: studyProgramId
          in: query
          description: ID of the study program that is being discussed
          required: true
          schema:
            type: integer
            format: int64
        - name: semester
          in: query
          description: semester that is being discussed
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A stream of message tokens
          content:
            text/event-stream:
              schema:
                type: string
                example: |
                  data: Hello

                  data: World
components:
  schemas:
    Semester:
      $ref: "../scraper/openapi.yaml#/components/schemas/Semester"

    StudyProgram:
      $ref: "../scraper/openapi.yaml#/components/schemas/StudyProgram"
    Module:
      $ref: "../scraper/openapi.yaml#/components/schemas/Module"

    ModuleCourses:
      $ref: "../scraper/openapi.yaml#/components/schemas/ModuleCourses"

    Course:
      $ref: "../scraper/openapi.yaml#/components/schemas/Course"

    Appointment:
      $ref: "../scraper/openapi.yaml#/components/schemas/Appointment"

    StudyProgramSelectorItem:
      type: object
      properties:
        title:
          type: string
        id:
          type: number
        semesters:
          type: array
          items:
            type: string
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
