openapi: 3.0.3
info:
  title: Scraper API
  version: 1.0.0
  description: API to query TUM courses

paths:
  /semesters:
    get:
      summary: Get all semesters
      responses:
        '200':
          description: List of semesters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Semester'

  /semesters/current:
    get:
      summary: Get the current semester
      responses:
        '200':
          description: The current semester
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Semester'

  /study-programs:
    get:
      summary: Get all study programs
      responses:
        '200':
          description: List of study programs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StudyProgram'

  /modules:
    get:
      summary: Get modules by program and semester
      parameters:
        - in: query
          name: study_id
          schema:
            type: integer
            format: int64
          required: true
          description: ID of the study program
        - in: query
          name: semesterKey
          schema:
            type: string
          required: true
          description: Key of the semester
      responses:
        '200':
          description: List of modules for the specified program and semester
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Module'

  /modules/{module_code}:
    get:
      summary: Get a module by its module code
      parameters:
        - in: path
          name: module_code
          required: true
          schema:
            type: string
          description: Code of the module to retrieve
      responses:
        '200':
          description: The requested module
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Module'
        '404':
          description: Module not found

components:
  schemas:
    Semester:
      type: object
      properties:
        semesterKey:
          type: string
          example: "2023FS"
        semesterTitle:
          type: string
          example: "Spring Semester 2023"
        semesterTag:
          type: string
          example: "spring"

    StudyProgram:
      type: object
      properties:
        study_id:
          type: string
          example: "CS101"
        program_name:
          type: string
          example: "Computer Science"
        degree_program_name:
          type: string
          example: "Bachelor of Science in Computer Science"
        degree_type_name:
          type: string
          example: "Bachelor"

    Language:
      type: object
      properties:
        name:
          type: string
          example: "Deutsch"
        nameEn:
          type: string
          example: "German"
        short:
          type: string
          example: "DE"
        shortEn:
          type: string
          example: "DE"

    Course:
      type: object
      properties:
        courseId:
          type: string
          example: "12345"
        title:
          type: string
          example: "Advanced Algorithms"
        lecturer:
          type: string
          example: "Prof. Dr. Example"
        type:
          type: string
          example: "Lecture"

    Module:
      type: object
      properties:
        module_id:
          type: string
          example: "CS123"
        module_code:
          type: string
          example: "CS123"
        module_title:
          type: string
          example: "Introduction to Programming"
        module_title_en:
          type: string
          example: "Introduction to Programming (EN)"
        module_content:
          type: string
          example: "Covers basics such as loops, variables, conditionals..."
        module_content_en:
          type: string
          example: "Covers basics such as loops, variables, conditionals... (EN)"
        module_outcome:
          type: string
          example: "Students can write basic code."
        module_outcome_en:
          type: string
          example: "Students can write basic code. (EN)"
        module_methods:
          type: string
          example: "Lecture, Exercises"
        module_methods_en:
          type: string
          example: "Lecture, Exercises (EN)"
        module_exam:
          type: string
          example: "Written exam"
        module_exam_en:
          type: string
          example: "Written exam (EN)"
        courses:
          type: object
          additionalProperties:
            type: array
            items:
              $ref: '#/components/schemas/Course'
