# .github/workflows/internal/release-service.yml
on:
  workflow_call:
    inputs:
      microservice:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      microservice: ${{ inputs.microservice }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: team-nixops
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix build .#${{ env.microservice }}.dockerImage

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run release for microservice container
        run: |
          echo "Releasing microservice: ${{ env.microservice }}"
          version=$(nix eval --raw .#${{ env.microservice }}.version)
          name=$(nix eval --raw .#${{ env.microservice }}.pname)
          LOCAL_IMAGE="nixops-${name}:${version}"
          REMOTE_VERSIONED_IMAGE="ghcr.io/aet-devops25/nixops-${name}:${version}"
          docker load < result
          docker tag $LOCAL_IMAGE $REMOTE_VERSIONED_IMAGE
          docker push $REMOTE_VERSIONED_IMAGE

      - name: Create and push git tag
        run: |
          version=$(nix eval --raw .#${{ env.microservice }}.version)
          name=$(nix eval --raw .#${{ env.microservice }}.pname)
          tag="${name}@v${version}"

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "$tag"
          git push origin "$tag"



