{
 "title": "TUM Scheduler",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "GenAI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "description": "per minute",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(\nhttp_requests_total{\njob=\"prometheus.scrape.genai\",\npath!~\"^/metrics/?$\"\n}[5m]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by (le) (\n  rate(http_request_duration_seconds_bucket{job=\"prometheus.scrape.genai\"}[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VectorDB Search Quality",
   "type": "timeseries",
   "description": "The average required number of rephrases per request",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "vecdb_rephrase_query_total{job=\"prometheus.scrape.genai\"} / vecdb_query_total{job=\"prometheus.scrape.genai\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "up{job=\"prometheus.scrape.genai\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Scraper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Scraping Duration",
   "type": "timeseries",
   "description": "per minute",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(\nscraper_duration_seconds_sum{\njob=\"prometheus.scrape.scraper\",\npath!~\"^/metrics/?$\"\n}[5m]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scraped Study Programs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "sum(scraper_study_programs_scraped_total{job=\"prometheus.scrape.scraper\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scraped Courses",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(scraper_courses_scraped_total{job=\"prometheus.scrape.scraper\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "up{job=\"prometheus.scrape.scraper\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Scraper Bridge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Embedded Courses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "embedding_bridge_study_programs_embedding_duration_seconds_sum{job=\"prometheus.scrape.embedding_bridge\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "expr": "up{job=\"prometheus.scrape.embedding_bridge\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}