# coding: utf-8

"""
    Sample API

    A sample API to illustrate OpenAPI concepts

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Sample API",
    description="A sample API to illustrate OpenAPI concepts",
    version="1.0.0",
)

app.include_router(DefaultApiRouter)
