# coding: utf-8

"""
    GenAI MicroService - OpenAPI 3.0

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.embedding_api import router as EmbeddingApiRouter
from openapi_server.apis.generation_api import router as GenerationApiRouter

app = FastAPI(
    title="GenAI MicroService - OpenAPI 3.0",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="0.0.1",
)

app.include_router(EmbeddingApiRouter)
app.include_router(GenerationApiRouter)
