apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: "{{ .Values.MonitoringNamespace }}"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-rbd-sc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus
  namespace: "{{ .Values.MonitoringNamespace }}"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-rbd-sc

