apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: "{{ .Values.MonitoringNamespace }}"
spec:
  type: ClusterIP
  selector:
    app: monitoring-selector
  ports:
    - port: 3000
      name: grafana
      targetPort: 3000
      protocol: TCP
    - port: 3100
      name: loki
      targetPort: 3100
      protocol: TCP
    - port: 9101
      name: inventor
      targetPort: 9101
      protocol: TCP
