name: Continuous Integration

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
      - 'embedding-bridge/**'
      - 'genai/**'
      - 'schedule-manager/**'
      - 'scraper/**'
      - 'schedule-optimizer/**'
      - 'nix/**'

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      client_changed: ${{ steps.check_diffs.outputs.client }}
      embedding_bridge_changed: ${{ steps.check_diffs.outputs.embedding-bridge }}
      genai_changed: ${{ steps.check_diffs.outputs.genai }}
      schedule_manager_changed: ${{ steps.check_diffs.outputs.schedule-manager }}
      scraper_changed: ${{ steps.check_diffs.outputs.scraper }}
      schedule_optimizer_changed: ${{ steps.check_diffs.outputs.schedule-optimizer }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - id: check_diffs
        run: |
          #TODO: add schedule-optimizer on merging https://github.com/AET-DevOps25/team-nixops/pull/39
          COMPONENTS=("client" "embedding-bridge" "genai" "schedule-manager" "scraper")
          for name in "${COMPONENTS[@]}"; do
            if git diff --name-only HEAD^ HEAD | grep "^${name}/"; then
              echo "${name}=true" >> $GITHUB_OUTPUT
            else
              echo "${name}=false" >> $GITHUB_OUTPUT
            fi
          done

  build-client:
    needs: check-changes
    if: needs.check-changes.outputs.client_changed == 'true'
    uses: ./.github/workflows/z-release-service.yml
    with:
      microservice: client
      version: false

  build-embedding-bridge:
    needs: check-changes
    if: needs.check-changes.outputs.embedding_bridge_changed == 'true'
    uses: ./.github/workflows/z-release-service.yml
    with:
      microservice: embedding-bridge
      version: false

  build-genai:
    needs: check-changes
    if: needs.check-changes.outputs.genai_changed == 'true'
    uses: ./.github/workflows/z-release-service.yml
    with:
      microservice: genai
      version: false

  build-schedule-manager:
    needs: check-changes
    if: needs.check-changes.outputs.schedule_manager_changed == 'true'
    uses: ./.github/workflows/z-release-service.yml
    with:
      microservice: schedule-manager
      version: false

  build-scraper:
    needs: check-changes
    if: needs.check-changes.outputs.scraper_changed == 'true'
    uses: ./.github/workflows/z-release-service.yml
    with:
      microservice: scraper
      version: false

  build-schedule-optimizer:
    needs: check-changes
    if: needs.check-changes.outputs.schedule_optimizer_changed == 'true'
    uses: ./.github/workflows/z-release-service.yml
    with:
      microservice: schedule-optimizer
      version: false

  integration-test:
    runs-on: ubuntu-latest
    needs:
      - build-client
      - build-embedding-bridge
      - build-genai
      - build-schedule-manager
      - build-scraper
      - build-schedule-optimizer
    if: >
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled') &&
      contains(needs.*.result, 'success')
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: team-nixops
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check -L --option sandbox false --no-pure-eval

  deploy:
    runs-on: ubuntu-latest
    needs:
      - integration-test
    if: >
      always() &&
      contains(needs.*.result, 'success')
    steps:
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/ec2.key
        chmod 600 ~/.ssh/ec2.key
        cat >>~/.ssh/config <<END
        Host ec2
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/ec2.key
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: root
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        SSH_HOST: ${{ vars.EC2_PUBLIC_IP }}
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: team-nixops
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Continuous Deployment on EC2
      run: |
        echo "${{ secrets.SOPS_PRIVATE_KEY }}" > key.txt
        export SOPS_AGE_KEY_FILE=key.txt
        nix profile install nixpkgs#nixos-rebuild
        nixos-rebuild switch --flake .#dev --target-host ec2
    - name: Run docker-compose on EC2
      run: |
        ssh ec2 << 'EOF'
          curl -L https://raw.githubusercontent.com/AET-DevOps25/team-nixops/refs/heads/main/docker-compose.yml -o docker-compose.yml
          docker compose pull
          docker compose up -d --force-recreate
        EOF

