name: "Deploy"
on:
  workflow_run:
    workflows: ["Build and Test GenAI"]
    types: 
      - completed
  # workflow_run:
  #   workflows: ["Build and Release GenAI Docker Image", "Build and Release Scraper Docker Image"]
  #   branches: [main]
  #   types: 
  #     - completed
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: team-nixops
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Determine versions
      id: det_versions
      run: |
        echo "genai=:$(nix eval --raw .#genai.version)\n" >> $GITHUB_OUTPUT
        # echo "client=$(nix eval --raw .#client.version)\n" >> $GITHUB_OUTPUT
    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'nixops'
        track: canary
        namespace: 'nixops-default'
        chart: './helm/Chart.yml'
        token: '${{ github.token }}'
        values: |
          # client:
          #   image:
          #     version: ${{ steps.det_versions.outputs.client }}
          genai:
            image:
              version: ${{ steps.det_versions.outputs.genai }}
        value-files: >-
        [
          "./helm/values.production.yaml"
        ]       
          
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
