name: "Deploy"
on:
  push:
  # workflow_run:
  #   workflows: ["Build and Test GenAI"]
  #   types: 
  #     - completed
  # workflow_run:
  #   workflows: ["Build and Release GenAI Docker Image", "Build and Release Scraper Docker Image"]
  #   branches: [main]
  #   types: 
  #     - completed
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: team-nixops
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - uses: azure/setup-helm@v4.3.0
    - name: Deploy
      run: |
        RELEASE_NAME="nixops"
        CHART_NAME="./helm"
        NAMESPACE="nixops-default"

        GENAI_VERSION="$(nix eval --raw .#genai.version)"
        CLIENT_VERSION="$(nix eval --raw .#client.version)"
        VAR_FLAGS="--values ./helm/values.ci.yaml --set genai.image.tag=$GENAI_VERSION --set client.image.tag=$CLIENT_VERSION"
        echo "Using GenAI version: $GENAI_VERSION"
        echo "Using Client version: $CLIENT_VERSION"

        TEMP_KUBECONFIG=$(mktemp)
        echo '${{ secrets.KUBECONFIG }}' > "$TEMP_KUBECONFIG" 
 
        helm upgrade --kubeconfig "$TEMP_KUBECONFIG"  "$RELEASE_NAME" "$CHART_NAME" -n "$NAMESPACE" --install $VAR_FLAGS
