name: "Build and Release Embedding-Bridge Docker Image"
on:
  push:
    branches:
      - main
    paths:
      - embedding-bridge/**
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: team-nixops
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#embedding-bridge.dockerImage
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Load and push Docker image
      run: |
        version=$(nix eval --raw .#embedding-bridge.version)
        name=$(nix eval --raw .#embedding-bridge.pname)
        LOCAL_IMAGE="nixops-${name}:${version}"
        REMOTE_VERSIONED_IMAGE="ghcr.io/aet-devops25/nixops-${name}:${version}"
        REMOTE_LATEST_IMAGE="ghcr.io/aet-devops25/nixops-${name}:latest"
        docker load < result
        docker tag $LOCAL_IMAGE $REMOTE_VERSIONED_IMAGE
        docker push $REMOTE_VERSIONED_IMAGE
        docker tag $LOCAL_IMAGE $REMOTE_LATEST_IMAGE
        docker push $REMOTE_LATEST_IMAGE

