name: "Lint Helm"
on:
  push:
    branches-ignore:
      - main
    paths:
      - helm/**
  pull_request:
    branches-ignore:
      - main
    paths:
      - helm/**
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/setup-helm@v4.3.0
    - run: cd helm && helm lint
