name: Merge Requirements

on:
  pull_request:
    branches-ignore:
      - main
  push:
    branches-ignore:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      client_changed: ${{ steps.check_diffs.outputs.client }}
      embedding_bridge_changed: ${{ steps.check_diffs.outputs.embedding-bridge }}
      genai_changed: ${{ steps.check_diffs.outputs.genai }}
      schedule_manager_changed: ${{ steps.check_diffs.outputs.schedule-manager }}
      scraper_changed: ${{ steps.check_diffs.outputs.scraper }}
      schedule_optimizer_changed: ${{ steps.check_diffs.outputs.schedule-optimizer }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - id: check_diffs
        run: |
          #TODO: add schedule-optimizer on merging https://github.com/AET-DevOps25/team-nixops/pull/39
          COMPONENTS=("client" "embedding-bridge" "genai" "schedule-manager" "scraper")
          for name in "${COMPONENTS[@]}"; do
            if git diff --name-only HEAD^ HEAD | grep "^${name}/"; then
              echo "${name}=true" >> $GITHUB_OUTPUT
            else
              echo "${name}=false" >> $GITHUB_OUTPUT
            fi
          done

  build-test-client:
    needs: check-changes
    if: needs.check-changes.outputs.client_changed == 'true'
    uses: ./.github/workflows/z-build-test-service.yml
    with:
      microservice: client

  build-test-embedding-bridge:
    needs: check-changes
    if: needs.check-changes.outputs.embedding_bridge_changed == 'true'
    uses: ./.github/workflows/z-build-test-service.yml
    with:
      microservice: embedding-bridge

  build-test-genai:
    needs: check-changes
    if: needs.check-changes.outputs.genai_changed == 'true'
    uses: ./.github/workflows/z-build-test-service.yml
    with:
      microservice: genai

  build-test-schedule-manager:
    needs: check-changes
    if: needs.check-changes.outputs.schedule_manager_changed == 'true'
    uses: ./.github/workflows/z-build-test-service.yml
    with:
      microservice: schedule-manager

  build-test-scraper:
    needs: check-changes
    if: needs.check-changes.outputs.scraper_changed == 'true'
    uses: ./.github/workflows/z-build-test-service.yml
    with:
      microservice: scraper

  build-test-schedule-optimizer:
    needs: check-changes
    if: needs.check-changes.outputs.schedule_optimizer_changed == 'true'
    uses: ./.github/workflows/z-build-test-service.yml
    with:
      microservice: schedule-optimizer

  lint-helm:
    uses: ./.github/workflows/z-lint-helm.yml
