name: Build and Test Microservice

on:
  workflow_call:
    inputs:
      microservice:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: team-nixops
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build Docker image
        run: |
          nix build .#${{ inputs.microservice }}.dockerImage

