on:
  workflow_call:
    inputs:
      microservice:
        required: true
        type: string
      version:
        required: false
        type: boolean
        default: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      microservice: ${{ inputs.microservice }}
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: team-nixops
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix build .#${{ env.microservice }}.dockerImage

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image (versioned or latest)
        run: |
          name=$(nix eval --raw .#${{ env.microservice }}.pname)

          version=$(nix eval --raw .#${{ env.microservice }}.version)
          if [[ "${{ inputs.version }}" == "true" ]]; then
            LOCAL_IMAGE="nixops-${name}:${version}"
            REMOTE_IMAGE="ghcr.io/aet-devops25/nixops-${name}:${version}"
          else
            LOCAL_IMAGE="nixops-${name}:${version}"
            REMOTE_IMAGE="ghcr.io/aet-devops25/nixops-${name}:latest"
          fi

          docker load < result
          docker tag "$LOCAL_IMAGE" "$REMOTE_IMAGE"
          docker push "$REMOTE_IMAGE"

      - name: Create and push git tag
        if: ${{ inputs.version }}
        run: |
          version=$(nix eval --raw .#${{ env.microservice }}.version)
          name=$(nix eval --raw .#${{ env.microservice }}.pname)
          tag="${name}@v${version}"

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "$tag"
          git push origin "$tag"
