apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus
  namespace: "{{ .Values.ServiceNamespace }}"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-rbd-sc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  namespace: "{{ .Values.ServiceNamespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd
  namespace: "{{ .Values.ServiceNamespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
