apiVersion: v1
kind: Service
metadata:
  name: genai-db-service
  namespace: "{{ .Values.ServiceNamespace }}"
spec:
  selector:
    app: genai-db-selector
  ports:
    - name: milvus
      port: 19530
      targetPort: 19530
      protocol: TCP
    - name: postgres
      port: 5432
      targetPort: 5432 
      protocol: TCP
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  type: ClusterIP
