apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nixops-genai-milvus
  namespace: "{{ .Values.ServiceNamespace }}"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-rbd-sc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nixops-genai-minio
  namespace: "{{ .Values.ServiceNamespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: csi-rbd-sc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nixops-genai-etcd
  namespace: "{{ .Values.ServiceNamespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-rbd-sc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nixops-genai-postgres
  namespace: "{{ .Values.ServiceNamespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-rbd-sc
