apiVersion: v1
kind: ConfigMap
metadata:
  name: genai-configmap
  namespace: "{{ .Values.ServiceNamespace }}"
data:
  genai_config_template.alloy: |
    livedebugging {
      enabled = true
    }
    local.file_match "files" {
    	path_targets = [{
    		__address__ = "localhost",
    		__path__    = "/app/logs/*.log",
    		app         = "genai",
    		environment = "{podname}",
    	}]
    }
    
    loki.source.file "files" {
    	targets               = local.file_match.files.targets
    	forward_to            = [loki.write.default.receiver]
    	legacy_positions_file = "/tmp/positions.yaml"
    }
    
    loki.write "default" {
    	endpoint {
    		url = "http://monitoring-service.nixops-monitoring.svc.cluster.local:3100/loki/api/v1/push"
    	}
    	external_labels = {}
    }
    prometheus.remote_write "default" {
      endpoint {
    		url = "http://monitoring-service.nixops-monitoring.svc.cluster.local:9090/api/v1/write"
      }
    }
    prometheus.scrape "default" {
      targets = [{
        __address__ = "127.0.0.1:8000",
      }]
      metrics_path    = "/metrics"
      forward_to = [prometheus.remote_write.default.receiver]
    }
  genai_db_config_template.yml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
      log_level: "debug"
    positions:
      filename: /tmp/positions.yaml
    clients: 
      - url: http://monitoring-service.{{ .Values.MonitoringNamespace }}.svc.cluster.local:3100/loki/api/v1/push
    scrape_configs:
      - job_name: files 
        static_configs: 
          - targets: 
              - localhost 
            labels:
              app: "milvus"
              environment: "{podname}" 
              __path__: /app/logs/*.log 
