apiVersion: v1
kind: Service
metadata:
  name: genai-service
  namespace: "{{ .Values.ServiceNamespace }}"
spec:
  selector:
    app: genai-selector
  ports:
    - name: genai
      port: {{ .Values.genai.service.port }}
      targetPort: {{ .Values.genai.service.targetPort }}
      protocol: TCP
    - name: alloy-web
      port: 12345
      targetPort: 12345 
      protocol: TCP
  type: {{ .Values.genai.service.type }}

