apiVersion: v1
kind: Service
metadata:
  name: genai-db-service
  namespace: "{{ .Values.ServiceNamespace }}"
spec:
  selector:
    app: genai-db-selector
  ports:
    - port: 19530
      targetPort: 19530
      protocol: TCP
  type: ClusterIP
